import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { build } from 'esbuild';

const templatePath = 'src/apps/dashboard/template.html';
const stylePath = 'src/apps/dashboard/style.css';
const clientPath = 'src/apps/dashboard/client.ts';
const outputPath = 'src/apps/generated/dashboard.ts';

function hash(value: string): string {
  return `sha256-${createHash('sha256').update(value).digest('base64')}`;
}

function replacePlaceholder(
  source: string,
  placeholder: string,
  value: string
): string {
  const occurrences = source.split(placeholder).length - 1;
  if (occurrences !== 1) {
    throw new Error(
      `Dashboard template must contain exactly one ${placeholder} placeholder.`
    );
  }
  return source.replace(placeholder, value);
}

const result = await build({
  entryPoints: [clientPath],
  bundle: true,
  format: 'esm',
  minify: true,
  platform: 'browser',
  target: ['es2022'],
  write: false,
  legalComments: 'none',
});

const [template, style] = await Promise.all([
  readFile(templatePath, 'utf8'),
  readFile(stylePath, 'utf8'),
]);
const script = new TextDecoder()
  .decode(result.outputFiles[0].contents)
  .replaceAll('</script', '<\\/script');
const csp = [
  "default-src 'none'",
  "img-src data:",
  `script-src '${hash(script)}'`,
  `style-src '${hash(style)}'`,
  "connect-src 'none'",
  "font-src 'none'",
  "object-src 'none'",
  "base-uri 'none'",
  "form-action 'none'",
].join('; ');

let html = replacePlaceholder(template, '__CSP__', csp);
html = replacePlaceholder(html, '__STYLE__', style);
html = replacePlaceholder(html, '__SCRIPT__', script);

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  `// Generated by scripts/build-dashboard.ts. Do not edit.\nexport const DASHBOARD_HTML = ${JSON.stringify(html)};\n`,
  'utf8'
);
